import project1 from "../assets/project/project1.png"
import project2 from "../assets/project/project2.png"
import project3 from "../assets/project/project3.png"
export const hero_content="I’m Shajahan Shaik, a software engineer skilled in Java,  full-stack development with React.js, Next.js, Node.js, and Express.js. I excel in data analysis, machine learning, and database management. A problem solver at heart, I’ve earned 9 LeetCode badges and am eager to contribute to impactful projects."
export const aboutme_content="Avid problem solver who thrives on challenges and loves turning ideas into fully functional full-stack websites. Currently excelling in my Master’s in Computer Science with a 4.0 GPA, I am passionate about coding, especially when it involves leetcoding and exploring new technologies. I enjoy contributing to open-source projects and constantly improving my skill set in areas like cloud computing, machine learning, and responsive web development. Eager to leverage my technical expertise, creativity, and collaborative mindset in a dynamic tech environment."

export const experience=[{year:"2022-2023",role:"WebDeveloper Intern",company:" VIT Vellore",description:"Developed an interactive web application using JavaScript and React.js to visually demonstrate 5 pathfinding algorithms, showcasing problem-solving skills and user experience design.",technologies:["React","Tailwind","JavaScript","TypeScript","Node","Express","MongoDB","Docker"]},{year:"2022-2023",role:"WebDeveloper Intern",company:" VIT Vellore",description:"Developed an interactive web application using JavaScript and React.js to visually demonstrate 5 pathfinding algorithms, showcasing problem-solving skills and user experience design.",technologies:["React","Tailwind","JavaScript","TypeScript","Node","Express","MongoDB","Docker"]}];
export const projects=[{title:"SmartPay Platform",github:"https://github.com/shajahanshaik915/smart-pay-platform.git",description:"Developed a payment platform with React, JavaScript, Express.js, and Node.js, integrating MongoDB to reduce transaction processing time by 20%. Enhanced user experience with intuitive design and navigation for seamless online payments.",technologies:[ "React"," Javascript", "Express.js", "Node.js", "MongoDB", "JWT"],image:project1},{title:"Medium-like Blogging Platform",github:"https://github.com/shajahanshaik915/mediumProject.git",description:"Developed a responsive blogging platform for web users to log in and post blogs. Implemented JWT authentication, enhancing server response times by 40% and ensuring type- safe schema validation with Zod and Prisma",technologies:[ "React", "TypeScript", "Cloudflare Workers", "Hono", "Zod", "Prisma"],image:project2},{title:"Simon Game",github:"https://github.com/shajahanshaik915/pattern-match-game.git",description:"Designed an interactive Simon game with dynamic animations and 5 unique sound effects. Implemented Simon game's core logic with features for pattern randomization, input checks, and immediate player feedback.",technologies:[ "React", "JavaScript", "TailwindCSS"],image:project3}]
export const education=[{institution:"University of Central Missouri", location:"Lee's Summit, US", course:"Computer Science", year: "2023-2025", coursework:"Relavent Course Work: Advanced Algorithms, Object-Oriented Programming, Data Structures and Algorithms ", cgpa:"CGPA: 4.0"}];
